#!/bin/sh
# Install isp-tv-agent on a Linux host (run as root).
# Usage: install.sh /path/to/isp-tv-agent [listen_addr]
#
# NEVER installs, upgrades, replaces, or restarts host ffmpeg / XtreamUI.
# Channels reuse whatever ffmpeg is already on the server.
set -eu

BIN_SRC="${1:?binary path required}"
LISTEN="${2:-:8099}"
DATA_DIR="${ISP_TV_DATA_DIR:-/var/lib/isp-tv}"
INSTALL_BIN="/usr/local/bin/isp-tv-agent"

if [ "$(id -u)" -ne 0 ]; then
  echo "must run as root" >&2
  exit 1
fi

if [ ! -f "$BIN_SRC" ]; then
  echo "binary not found: $BIN_SRC" >&2
  exit 1
fi

# Resolve existing ffmpeg only — do not apt/yum/install anything.
FFMPEG_BIN=""
if command -v ffmpeg >/dev/null 2>&1; then
  FFMPEG_BIN="$(command -v ffmpeg)"
elif [ -x /usr/bin/ffmpeg ]; then
  FFMPEG_BIN=/usr/bin/ffmpeg
elif [ -x /usr/local/bin/ffmpeg ]; then
  FFMPEG_BIN=/usr/local/bin/ffmpeg
elif [ -x /home/xtreamcodes/iptv_xtream_codes/php/bin/ffmpeg ]; then
  FFMPEG_BIN=/home/xtreamcodes/iptv_xtream_codes/php/bin/ffmpeg
elif [ -x /home/xtreamcodes/iptv_xtream_codes/bin/ffmpeg ]; then
  FFMPEG_BIN=/home/xtreamcodes/iptv_xtream_codes/bin/ffmpeg
fi

if [ -z "$FFMPEG_BIN" ]; then
  echo "ERROR: no existing ffmpeg found (PATH / usr / XtreamUI). Refusing to install a package — install ffmpeg yourself or keep Xtream's binary." >&2
  exit 1
fi
echo "ISP_TV_FFMPEG=$FFMPEG_BIN (reusing existing; not installing)"

id isp-tv >/dev/null 2>&1 || useradd --system --home "$DATA_DIR" --shell /usr/sbin/nologin isp-tv

mkdir -p "$DATA_DIR/logos" "$DATA_DIR/run" "$DATA_DIR/scripts"
install -m 0755 "$BIN_SRC" "$INSTALL_BIN"

if [ ! -f "$DATA_DIR/api.token" ]; then
  umask 077
  # token generated by agent on first start if missing; pre-create for install capture
  TOKEN="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 32)"
  printf '%s\n' "$TOKEN" > "$DATA_DIR/api.token"
  chmod 600 "$DATA_DIR/api.token"
fi

chown -R isp-tv:isp-tv "$DATA_DIR"

cat > /etc/systemd/system/isp-tv-agent.service <<EOF
[Unit]
Description=ISP Control TV agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
Environment=ISP_TV_DATA_DIR=$DATA_DIR
Environment=ISP_TV_LISTEN=$LISTEN
ExecStart=$INSTALL_BIN -data-dir $DATA_DIR -listen $LISTEN
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

# Only (re)starts isp-tv-agent — never touches XtreamUI / ffmpeg packages.
systemctl daemon-reload
systemctl enable isp-tv-agent.service
systemctl restart isp-tv-agent.service

sleep 1
TOKEN="$(tr -d '\n' < "$DATA_DIR/api.token")"
echo "ISP_TV_INSTALL_OK"
echo "ISP_TV_TOKEN=$TOKEN"
echo "ISP_TV_LISTEN=$LISTEN"
echo "ISP_TV_FFMPEG=$FFMPEG_BIN"
echo "ISP_TV_VERSION=$("$INSTALL_BIN" -h 2>&1 | head -1 || echo 0.1.0)"
